# Generated by Django 5.0.7 on 2024-07-23 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50, unique=True)),
                ('project_company', models.CharField(default='', max_length=50)),
                ('project_name', models.CharField(max_length=50)),
                ('project_time_period', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=10)),
                ('EXWLocation', models.BooleanField(default=False)),
                ('filtered_df_json', models.TextField(default='{}')),
                ('distances_df_json', models.TextField(default='{}')),
                ('modified_transactions_df_json', models.TextField(default='{}')),
                ('modified_transactions_day_df_json', models.TextField(default='{}')),
                ('baseline_infoTable_df_json', models.TextField(default='{}')),
                ('radiusTable_df_json', models.TextField(default='{}')),
                ('transport_cost_df_json', models.TextField(default='{}')),
                ('reduced_customers_df_json', models.TextField(default='{}')),
                ('small_customers_df_json', models.TextField(default='{}')),
                ('NO_Baseline_Raw_Results_df_json', models.TextField(default='{}')),
                ('Transport_Cost_per_Customer_df_json', models.TextField(default='{}')),
                ('NO_Baseline_Customer_Results_df_json', models.TextField(default='{}')),
                ('NO_Baseline_Gross_Sales', models.IntegerField(default=0)),
                ('NO_Baseline_Done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quarry',
            fields=[
                ('quarry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=25)),
                ('clusterToBox_df_json', models.TextField(default='{}')),
                ('clusterToBox_df_change', models.BooleanField(default=False)),
                ('productSalesVolume_df_json', models.TextField(default='{}')),
                ('productAggLevy_df_json', models.TextField(default='{}')),
                ('productProdVolume_df_json', models.TextField(default='{}')),
                ('productProductCluster_df_json', models.TextField(default='{}')),
                ('costBoxProdVolume_df_json', models.TextField(default='{}')),
                ('productListFull_df_json', models.TextField(default='{}')),
                ('PLAllocationData_df_json', models.TextField(default='{}')),
                ('P4PFullSummary_df_json', models.TextField(default='{}')),
                ('productComposition_df_json', models.TextField(default='{}')),
                ('constituentModesBalance_df_json', models.TextField(default='{}')),
                ('capacityModes_df_json', models.TextField(default='{}')),
                ('salesSimulation_df_json', models.TextField(default='{}')),
                ('minVC_Simulation_Table_df_json', models.TextField(default='{}')),
                ('modes_Hours_minVC_Simulation_df_json', models.TextField(default='{}')),
                ('maxGM_Simulation_Table_df_json', models.TextField(default='{}')),
                ('modes_Hours_maxGM_Simulation_df_json', models.TextField(default='{}')),
                ('startingMonth', models.CharField(default='', max_length=50)),
                ('finalMonth', models.CharField(default='', max_length=50)),
                ('FarSeer_stockInfo_df_json', models.TextField(default='{}')),
                ('maxOpeningHours_df_json', models.TextField(default='{}')),
                ('salesForecast_df_json', models.TextField(default='{}')),
                ('FarSeer_meetAllSales_results_df_json', models.TextField(default='{}')),
                ('FarSeer_meetAllSales_hours_df_json', models.TextField(default='{}')),
                ('FarSeer_meetForcedSales_results_df_json', models.TextField(default='{}')),
                ('FarSeer_meetForcedSales_hours_df_json', models.TextField(default='{}')),
                ('FarSeer_maxGM_results_df_json', models.TextField(default='{}')),
                ('FarSeer_maxGM_hours_df_json', models.TextField(default='{}')),
                ('FarSeer_MeetAllSales_OptimisationSuccess', models.BooleanField(default=True)),
                ('FarSeer_MeetForcedSales_OptimisationSuccess', models.BooleanField(default=True)),
                ('FarSeer_MaxGM_OptimisationSuccess', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(to='QuarryIQ.projectdata')),
            ],
        ),
        migrations.AddField(
            model_name='projectdata',
            name='quarries',
            field=models.ManyToManyField(to='QuarryIQ.quarry'),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('scenario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=100)),
                ('optimisation_type', models.CharField(choices=[('meeting_all_sales', 'Meeting All Sales'), ('max_gross_margin', 'Maximizing Gross Margin')], default='meeting_all_sales', max_length=20)),
                ('scenario_infoTable_df_json', models.TextField(default='{}')),
                ('NO_Scenario_Raw_Results_df_json', models.TextField(default='{}')),
                ('NO_Scenario_Customer_Results_df_json', models.TextField(default='{}')),
                ('NO_Scenario_Done', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='QuarryIQ.projectdata')),
            ],
        ),
    ]
